# docker-compose.yml
version: '3.8'
services:
  mini-soar-app:
    build: .
    container_name: mini-soar
    ports:
      - "8501:8501"
    volumes:
      # Mount the entire project directory for instant code changes
      - .:/app
    # This command runs our training script first, then starts the app
    command: /bin/sh -c "python train_model.py && streamlit run app.py --server.fileWatcherType none"